# const of fields ,the starting f stands for fields
fIMPLSTATUS='implStatus'
fOPERSTATUS='operStatus'
fZMAPSTATUS='zmapStatus'
fPROGRESS='progress'
f_ID='_id'
fNODETASKID='nodeTaskId'
fPLUGIN='plugin'
fNAME='name'
fIPTOTAL='ipTotal'
fTHREADDEMAND='threadDemand'
fTHREADALLOT='threadAllot'
fKEYLOG='keyLog'
fNEEDTOSYNC='needToSync'

#const of status values, the starting s stands for status
sCOMPLETE='complete'
sNEW='new'
sWAITING='waiting'
sWRONG='wrong'
sRUN='run'
sPAUSE='pause'
sDELETE='delete'
sRUNNING='running'