# const of fields ,the starting f stands for fields

fZMAPRUNNING='zmapRunning'
fNEEDTOSYNC='needToSync'
fGOWRONG='goWrong'
fZMAPCOMPLETE='zmapComplete'
fPAUSED='paused'
f_ID='_id'
fNODETASKID='nodeTaskId'
fTASKNAME='taskName'
fPLUGIN='plugin'
fNAME='name'
fZMAPRANGE='zmapRange'
fZMAPPROGRESS='zmapProgress'
fSCANRANGE='scanRange'
fZMAPCOMPLETE='zmapComplete'

fTHREADDEMAND='threadsDemand'
fTHREADALLOT='threadsAllot'
fKEYLOG='keyLog'
fZMAPTOTAL='zmapTotal'

#const of status values, the starting s stands for status
sCOMPLETE='complete'
sNEW='new'
sWAITING='waiting'
sWRONG='wrong'
sRUN='run'
sPAUSE='pause'
sDELETE='delete'
sRUNNING='running'